### ISSUE TITLE
Will not connect

### ISSUE THREAD

**Issue by Glasairmell** [schmittx/home-assistant-resideo-total-connect#1]
Installs fine. Will not connect.  Thanks for the effort.

**Comment by schmittx** [comment]
It works fine for me, I have no plans to maintain this repo for others' usage. Please fork and modify as needed.

**Comment by jotadesigns** [comment]
same @schmittx :(
still working for you? 

![image](https://github.com/user-attachments/assets/2e2b9e43-1eb5-4cbf-8777-51df5f49a1cb)

![image](https://github.com/user-attachments/assets/17fec129-26be-4d48-b598-c9bfad75d3f4)


thanks!

**Comment by schmittx** [comment]
Yeah, still working fine for me. What do the debug logs show?
