### ISSUE TITLE
I can't make this work for my T5 at all...

### ISSUE THREAD

**Issue by trippme** [schmittx/home-assistant-resideo-total-connect#2]
I've installed this and configured it (as best I can see what to do) and I don't seem to have access to my thermostat.
![Screenshot 2024-12-19 101158](https://github.com/user-attachments/assets/a154beb4-2b02-4b24-a88b-c798e49510b0)

Could use some help/advice on what I'm doing wrong.

**Comment by schmittx** [comment]
This integration only supports Resideo security systems (similar to the core Home Assistant integration), it does not support any thermostats or other devices.

**Comment by trippme** [comment]
Shoot, I miss read that.  Thanks for the response!
